---

- name: Create volume group
  lvg: 
    vg: extvg 
    pvs: "/dev/{{ device_name }}"

- name: Create lvm group
  lvol: 
    vg: "{{ volume_group_name }}"
    lv: "{{ logical_volume_name }}"
    size: "{{ logical_volume_size }}"
    shrink: False
    state: present

- name: Create filesystem
  filesystem: 
    fstype: "{{ file_system_type }}"
    dev: "/dev/mapper/{{ volume_group_name }}-{{ logical_volume_name }}"

- name: "Create {{ volume_mount_point }}"
  file: 
    path: "{{ volume_mount_point }}"
    state: directory

- name: Edit fstab
  mount: 
    name: "{{ volume_mount_point }}"
    src: "/dev/mapper/{{ volume_group_name }}-{{ logical_volume_name }}"
    fstype: "{{ file_system_type }}"
    opts: "{{ fstab_options }}"
    dump: 1
    passno: 2
    state: present